routing:
  index:
    # url pattern to match
    path: ^\/$
    # if this rounting is secure
    isSecure: 0
    # which controller should be assigned
    controller: frontend/index
    

  admin:
    path: ^\/admin(\/)?$
    isSecure: 1
    controller: backend/index
  backend_delete:
    path: ^\/admin\/delete\/([^\/]+)\/(\d+)\/?$
    isSecure: 1
    controller: backend/delete
  sydneytoday_dingtie_index:
    path: ^\/admin\/sydneytoday\/dingtie\/?$
    isSecure: 1
    controller: backend/sydneytoday/dingtie/index
  sydneytoday_dingtie_list:
    path: ^\/admin\/sydneytoday\/dingtie\/list\/?$
    isSecure: 1
    controller: backend/sydneytoday/dingtie/list
  sydneytoday_dingtie_add:
    path: ^\/admin\/sydneytoday\/dingtie\/add\/?$
    isSecure: 1
    controller: backend/sydneytoday/dingtie/add_edit
  sydneytoday_dingtie_edit:
    path: ^\/admin\/sydneytoday\/dingtie\/edit\/(\d+)\/?$
    isSecure: 1
    controller: backend/sydneytoday/dingtie/add_edit
  sydneytoday_deal_index:
    path: ^\/admin\/sydneytoday\/deal\/?$
    isSecure: 1
    controller: backend/sydneytoday/deal/index
  sydneytoday_deal_list:
    path: ^\/admin\/sydneytoday\/deal\/list\/?$
    isSecure: 1
    controller: backend/sydneytoday/deal/list
  sydneytoday_deal_add:
    path: ^\/admin\/sydneytoday\/deal\/add\/?$
    isSecure: 1
    controller: backend/sydneytoday/deal/add_edit
  sydneytoday_deal_edit:
    path: ^\/admin\/sydneytoday\/deal\/edit\/(\d+)\/?$
    isSecure: 1
    controller: backend/sydneytoday/deal/add_edit
  sydneytoday_deal_instance_add:
    path: ^\/admin\/sydneytoday\/deal\/(\d+)\/instance\/add\/?$
    isSecure: 1
    controller: backend/sydneytoday/deal/instance/add
    
    
  login:
    path: ^\/login$
    isSecure: 0
    controller: login
  logout:
    path: ^\/logout$
    isSecure: 0
    controller: logout
    