routing:
  index:
    # url pattern to match
    path: ^\/$
    # if this rounting is secure
    isSecure: 0
    # which controller should be assigned
    controller: frontend/index
  
  
  groupon_tracking:
    path: ^\/deal\/(\d+)\/tracking\/?$
    isSecure: 0
    controller: frontend/groupon/tracking
  

  admin:
    path: ^\/admin(\/)?$
    isSecure: 1
    controller: backend/index
  backend_delete:
    path: ^\/admin\/delete\/([^\/]+)\/(\d+)\/?$
    isSecure: 1
    controller: backend/delete
  backend_valid:
    path: ^\/admin\/validate\/([^\/]+)\/(\d+)\/?$
    isSecure: 1
    controller: backend/validate
    
    
    
  backend_deal_index:
    path: ^\/admin\/deal\/?$
    isSecure: 1
    controller: backend/deal/index
  backend_deal_list:
    path: ^\/admin\/deal\/list\/?$
    isSecure: 1
    controller: backend/deal/list
  backend_deal_add:
    path: ^\/admin\/deal\/add\/?$
    isSecure: 1
    controller: backend/deal/add_edit
  backend_deal_edit:
    path: ^\/admin\/deal\/edit\/(\d+)\/?$
    isSecure: 1
    controller: backend/deal/add_edit
  backend_deals_sydneytoday_discount_deal_instance_add:
    path: ^\/admin\/deal\/(\d+)\/sydneytoday\/discount_deal\/instance\/add\/?$
    isSecure: 1
    controller: backend/deal/sydneytoday/discount_deal_add
  backend_deals_sydneytoday_newproduct_deal_instance_add:
    path: ^\/admin\/deal\/(\d+)\/sydneytoday\/newproduct\/instance\/add\/?$
    isSecure: 1
    controller: backend/deal/sydneytoday/newproduct_deal_add
    
  backend_sydneytoday:
    path: ^\/admin\/sydneytoday\/?$
    isSecure: 1
    controller: backend/sydneytoday/index
  backend_sydneytoday_user_cookie_delete:
    path: ^\/admin\/sydneytoday\/user\/flush-cookie\/?$
    isSecure: 1
    controller: backend/user/cookie_delete
    
  backend_sydneytoday_deal:
    path: ^\/admin\/sydneytoday\/deal\/?$
    isSecure: 1
    controller: backend/sydneytoday/deal/index
  backend_sydneytoday_deal_list:
    path: ^\/admin\/sydneytoday\/deal\/list\/?$
    isSecure: 1
    controller: backend/sydneytoday/deal/list
  backend_sydneytoday_newproduct:
    path: ^\/admin\/sydneytoday\/newproduct\/?$
    isSecure: 1
    controller: backend/sydneytoday/newproduct/index
  backend_sydneytoday_newproduct_list:
    path: ^\/admin\/sydneytoday\/newproduct\/list\/?$
    isSecure: 1
    controller: backend/sydneytoday/newproduct/list
    
    
    
    
  frontend_deal_details:
    path: ^\/deal\/([^\/]+)\/(\d+)\/?$
    isSecure: 0
    controller: frontend/deal/details
  frontend_deal_img_crop:
    path: ^\/deal\/([^\/]+)\/(\d+)\/crop(\/refill)?$
    isSecure: 1
    controller: frontend/img_crop
  frontend_deals:
    path: ^\/deals(\/([^\/]+))?$
    isSecure: 0
    controller: frontend/deal/list
  frontend_gotodeal:
    path: ^\/go\/to\/deal\/(\d+)\/?$
    isSecure: 0
    controller: frontend/gotodeal
  frontend_contact:
    path: ^\/contact\-us\/?$
    isSecure: 0
    controller: frontend/pages/contact
  frontend_ajax_spam_validate:
    path: ^\/spam\/validate\/?$
    isSecure: 0
    controller: frontend/spam_validate
  frontend_ajax_wechat_share_confirm:
    path: ^\/wechat\/share_confirm?$
    isSecure: 0
    controller: frontend/wechat/share_confirm
    
  search:
    path: ^\/search\/deal$
    isSecure: 0
    controller: frontend/deal/search
    
    
  login:
    path: ^\/login$
    isSecure: 0
    controller: login
  logout:
    path: ^\/logout$
    isSecure: 0
    controller: logout
    
    
  api_wechat:
    path: ^\/api\/wechat$
    isSecure: 0
    controller: api/wechat