routing:
  index:
    # url pattern to match
    path: ^\/$
    # if this rounting is secure
    isSecure: 0
    # which controller should be assigned
    controller: frontend/index
  
  
  groupon_tracking:
    path: ^\/deal\/(\d+)\/tracking\/?$
    isSecure: 0
    controller: frontend/groupon/tracking
  

  admin:
    path: ^\/admin(\/)?$
    isSecure: 1
    controller: backend/index
  backend_delete:
    path: ^\/admin\/delete\/([^\/]+)\/(\d+)\/?$
    isSecure: 1
    controller: backend/delete
  backend_valid:
    path: ^\/admin\/validate\/([^\/]+)\/(\d+)\/?$
    isSecure: 1
    controller: backend/validate
  user_cookie_delete:
    path: ^\/admin\/sydneytoday\/user\/flush-cookie\/?$
    isSecure: 1
    controller: backend/user/cookie_delete
    
    
    
  sydneytoday_index:
    path: ^\/admin\/sydneytoday\/?$
    isSecure: 1
    controller: backend/sydneytoday/index
  sydneytoday_dingtie_index:
    path: ^\/admin\/sydneytoday\/dingtie\/?$
    isSecure: 1
    controller: backend/sydneytoday/dingtie/index
  sydneytoday_dingtie_list:
    path: ^\/admin\/sydneytoday\/dingtie\/list\/?$
    isSecure: 1
    controller: backend/sydneytoday/dingtie/list
  sydneytoday_dingtie_add:
    path: ^\/admin\/sydneytoday\/dingtie\/add\/?$
    isSecure: 1
    controller: backend/sydneytoday/dingtie/add_edit
  sydneytoday_dingtie_edit:
    path: ^\/admin\/sydneytoday\/dingtie\/edit\/(\d+)\/?$
    isSecure: 1
    controller: backend/sydneytoday/dingtie/add_edit
  sydneytoday_deal_index:
    path: ^\/admin\/sydneytoday\/deal\/?$
    isSecure: 1
    controller: backend/sydneytoday/deal/index
  sydneytoday_deal_list:
    path: ^\/admin\/sydneytoday\/deal\/list\/?$
    isSecure: 1
    controller: backend/sydneytoday/deal/list
  sydneytoday_deal_add:
    path: ^\/admin\/sydneytoday\/deal\/add\/?$
    isSecure: 1
    controller: backend/sydneytoday/deal/add_edit
  sydneytoday_deal_edit:
    path: ^\/admin\/sydneytoday\/deal\/edit\/(\d+)\/?$
    isSecure: 1
    controller: backend/sydneytoday/deal/add_edit
  sydneytoday_deal_instance_add:
    path: ^\/admin\/sydneytoday\/deal\/(\d+)\/instance\/add\/?$
    isSecure: 1
    controller: backend/sydneytoday/deal/instance/add
    
    
    
  backend_deal_index:
    path: ^\/admin\/deal\/?$
    isSecure: 1
    controller: backend/deal/index
  backend_deal_list:
    path: ^\/admin\/deal\/list\/?$
    isSecure: 1
    controller: backend/deal/list
  backend_deal_add:
    path: ^\/admin\/deal\/add\/?$
    isSecure: 1
    controller: backend/deal/add_edit
  backend_deal_edit:
    path: ^\/admin\/deal\/edit\/(\d+)\/?$
    isSecure: 1
    controller: backend/deal/add_edit
  backend_deals_sydneytoday_discount_deal_instance_add:
    path: ^\/admin\/deal\/(\d+)\/sydneytoday\/discount_deal\/instance\/add\/?$
    isSecure: 1
    controller: backend/deal/sydneytoday/discount_deal_add
    
    
    
    
  frontend_deal_details:
    path: ^\/deal\/([^\/]+)\/(\d+)$
    isSecure: 0
    controller: frontend/deal/details
  frontend_deals:
    path: ^\/deals(\/([^\/]+))?$
    isSecure: 0
    controller: frontend/deal/list
  frontend_gotodeal:
    path: ^\/go\/to\/deal\/(\d+)\/?$
    isSecure: 0
    controller: frontend/gotodeal
  frontend_contact:
    path: ^\/contact\-us\/?$
    isSecure: 0
    controller: frontend/pages/contact
  frontend_ajax_spam_validate:
    path: ^\/spam\/validate\/?$
    isSecure: 0
    controller: frontend/spam_validate
    
  search:
    path: ^\/search\/deal$
    isSecure: 0
    controller: frontend/deal/search
    
    
  login:
    path: ^\/login$
    isSecure: 0
    controller: login
  logout:
    path: ^\/logout$
    isSecure: 0
    controller: logout
    