#site_url
site_url: http://sydneytoday.websitesydney.net
tracking_site_url: http://tracking.hosterdiy.com

#backend user, username:password
backend_user:
  admin: numb3r1
  
# pagination
pagination_range: 5
record_each_page: 50

# Local database settings
mysql_host: localhost
mysql_user: sydneytoday
mysql_pass: Osdiojoewsefe29)8
mysql_db: sydneytoday

# Sydney today username and password
sydneytoday:
  username: jeangirl186@163.com
  password: 0172122a
  loginurl: http://www.sydneytoday.com/do/login.php?f
  qaptcha_url: http://www.sydneytoday.com/qaptcha/Qaptcha.jquery.php
  post_url: http://www.sydneytoday.com/post.php?action=postnew

# curl user-agent
curl:
  useragent: Mozilla/4.0 (compatible; MSIE 5.01; Windows NT 5.0)
  
# category // -- see bootstrap.php for initialization
category:
  food: 美食
  goods: 商品
  travel: 旅游
  event: 活动